[project]
name = "simple-etl"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dataclasses>=0.8",
    "geopy>=2.4.1",
    "loguru>=0.7.3",
    "pathlib>=1.0.1",
    "requests>=2.32.3",
    "ruff>=0.9.7",
]
